# Generated by Django 4.1.5 on 2023-02-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.photos'),
            preserve_default=False,
        ),
    ]
