# Generated by Django 4.1.5 on 2023-02-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], related_name='photos', to='album.tag'),
        ),
    ]
