# Generated by Django 4.1.5 on 2023-02-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_photos_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='photos',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='album.tag'),
            preserve_default=False,
        ),
    ]
