# Generated by Django 4.1.5 on 2023-02-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_remove_tag_photo_remove_photos_tags_alter_tag_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='photos',
            name='tags',
            field=models.ManyToManyField(to='album.tag'),
        ),
    ]
