# Generated by Django 4.1.5 on 2023-02-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_remove_photos_tags_alter_tag_title_photos_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.photos'),
            preserve_default=False,
        ),
    ]
